#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import vm from "node:vm";
const [conceptData,sourceData,journey]=await Promise.all([
 "knowledge-graph/concepts.json","knowledge-graph/research-sources.json","knowledge-graph/research-journey.json"
].map(async p=>JSON.parse(await fs.readFile(p,"utf8"))));
const win={};const context=vm.createContext({window:win,URL,console});
vm.runInContext(await fs.readFile("research-models.js","utf8"),context);
vm.runInContext(await fs.readFile("research-experience.js","utf8"),context);
const M=win.AtlasResearchModels,X=win.AtlasResearchExperience;
assert.equal(X.validate(journey,conceptData.concepts,sourceData.sources),true);
assert.equal(journey.stages.length,6);
assert.equal(new Set(journey.stages.flatMap(s=>s.conceptIds)).size>18,true,"One pathway connects many actual mapped concepts");
assert.equal(journey.problems.length,30,"Six research stages each have five independently authored reasoning problems");
for(const s of journey.stages)assert.equal(journey.problems.filter(p=>s.conceptIds.includes(p.conceptId)).length,5,"Exactly five authored deep problems for "+s.id);
assert.ok(journey.relationships.some(e=>e.kind==="causal")&&journey.relationships.some(e=>e.kind==="application")&&journey.relationships.some(e=>e.kind==="prerequisite"));
let r=M.kick({k:0,f:0,angle:0});
assert.equal(r.bound,true);assert.ok(Math.abs(r.energy+.5)<1e-12);assert.ok(Math.abs(r.ecc)<1e-10);assert.ok(Math.abs(r.a-1)<1e-10);
assert.equal(M.kick({k:0,f:.5}).bound,null,"Losing exactly half the gravitational mass in this initial toy circular orbit gives parabolic energy");
assert.equal(M.kick({k:.5,angle:0,f:0}).bound,false);
assert.equal(M.kick({k:.5,angle:180,f:0}).bound,true);
const c=M.chirp({m1:10,m2:10,forb:20});
assert.ok(Math.abs(c.mc-10/2**.2)<1e-10);assert.equal(c.fgw,40);assert.ok(c.tSec>0&&c.fDot>0);
assert.ok(Math.abs(M.chirp({m1:10,m2:10,forb:40}).tSec/c.tSec-2**(-8/3))<1e-10);
assert.equal(M.envelope({released:15,required:10,alpha:.6}).budgetMet,false);
assert.ok(Math.abs(M.roche({donor:10,accretor:10,radius:1,a:10}).lobe/10-.37892)<.002);
const selected=M.selection({a:100,b:100,pa:.8,pb:.2});
assert.equal(selected.da,80);assert.equal(selected.db,20);assert.equal(selected.intrinsic,.5);assert.ok(Math.abs(selected.detected-.8)<1e-12);
const d=M.delays({t1:2,t2:5,delay:3,mass1:1000,mass2:2000,yieldPer1000:1});
assert.equal(d.count1,1);assert.equal(d.count2,2);assert.equal(d.merge1,5);assert.equal(d.merge2,8);
assert.equal(M.delays({t1:2,t2:5,delay:0}).merge1,2,"A zero-delay cohort merges at its birth epoch in this discrete toy limit");
const p=M.population({n:100,seed:42}),p2=M.population({n:100,seed:42});
assert.equal(p.candidate+p.unbound+p.wide,100);
assert.deepEqual(JSON.parse(JSON.stringify(p.rows)),JSON.parse(JSON.stringify(p2.rows)),"Same seed reproduces synthetic records");
assert.notDeepEqual(JSON.parse(JSON.stringify(p.rows)),JSON.parse(JSON.stringify(M.population({n:100,seed:43}).rows)));
assert.equal(p.rows.length,100,"Every synthetic system is retained for reproducible export");assert.ok(/not|Not/.test(p.caveat),"Toy outcomes do not claim real simulated binaries");
const units=[{id:"unit",objectives:[{id:"a",component:"conceptual"},{id:"b",component:"quantitative"}]}];
const now=1_000_000_000;
const e=M.evidence([{unitId:"unit",objectiveId:"a",correct:false,at:now-2*86400000},{unitId:"unit",objectiveId:"b",correct:true,at:now}],units,now);
assert.equal(e.conceptual.attempts,1);assert.equal(e.conceptual.correct,0);assert.equal(e.conceptual.due,1);
assert.equal(e.quantitative.correct,1);
const handlers={};const host={innerHTML:"",addEventListener:(name,fn)=>handlers[name]=fn,querySelector:()=>null};
const saved=new Map();const storage={getItem:key=>saved.get(key)||null,setItem:(key,value)=>saved.set(key,value)};
let selectedConcept="",openedPractice="";
let instance=X.mount({host,data:journey,concepts:conceptData.concepts,sources:sourceData.sources,
 model:M,storage,getEvidence:()=>e,openConcept:id=>selectedConcept=id,openPractice:id=>openedPractice=id});
assert.match(host.innerHTML,/Choose a research question to explore/,"No fixed first-step hero");
assert.equal(instance.snapshot().stage,null,"No question automatically selected");
assert.equal((host.innerHTML.match(/data-stage="/g)||[]).length,6,"All six questions are visible at once");
assert.doesNotMatch(host.innerHTML,/class="research-stage-detail"|CURRENT STAGE|Suggested earlier stage/,"No selected detail or prerequisite nudge until the learner chooses");
assert.doesNotMatch(host.innerHTML,/>0[1-6] · |Start with a real binary|FIELD-TO-RESEARCH PATHWAY/,"Cards are questions, not numbered stages");
assert.ok(journey.stages.every(s=>s.name.endsWith("?")&&!Object.hasOwn(s,"prior")),"Six unnumbered, independently selectable research questions");
// Select the LAST question first: research entry points must be truly non-linear.
handlers.click({target:{closest:()=>({dataset:{stage:"inference"}})}});
assert.equal(instance.snapshot().stage,"inference","Clicking a non-first card opens exactly that question");
assert.match(host.innerHTML,/OPEN QUESTION/);
assert.match(host.innerHTML,/INTERACTIVE PHYSICS LAB/);
assert.ok(host.innerHTML.includes("Cosmic birth-to-merger delays"),"Seventh toy model remains selectable");
assert.match(host.innerHTML,/role="img"/,"Selected question includes a live educational SVG");
assert.match(host.innerHTML,/BROWSER-LOCAL RESEARCH WORKSPACE/);
assert.match(host.innerHTML,/CURATED READING SEQUENCE/);
assert.match(host.innerHTML,/RESEARCH REASONING/);
assert.equal((host.innerHTML.match(/class="research-problem"/g)||[]).length,5,"Five authored problems for the chosen question");
assert.equal((host.innerHTML.match(/class="research-problem" open/g)||[]).length,1,"Only the first problem within the chosen question starts open");
assert.match(host.innerHTML,/data-concept="detector-selection-effects"/,"Concept review matches the selected question");
handlers.click({target:{closest:()=>({dataset:{stage:"inference"}})}});
assert.equal(instance.snapshot().stage,null,"Clicking the open card again collapses the question");
assert.doesNotMatch(host.innerHTML,/class="research-stage-detail"/,"Collapsing returns to only the choice cards");
instance.selectStage("population");
assert.equal(instance.snapshot().stage,"population");
assert.match(host.innerHTML,/simulation onboarding notebook/);
assert.match(host.innerHTML,/Open any question in any order/,"Question selection is never gated by prior selections");
assert.match(host.innerHTML,/Synthetic|synthetic/);
assert.equal(instance.snapshot().done.length,0,"No unsupported implicit mastery or completed stages");
handlers.click({target:{closest:()=>({dataset:{action:"done"}})}});
assert.equal(instance.snapshot().done.length,1);
assert.equal(JSON.parse(saved.get("research-atlas-research-workspace-v1")).done[0],"population");
instance.selectStage("inference");assert.equal(instance.snapshot().stage,"inference");
assert.match(host.innerHTML,/Detector Selection|Detection/);
handlers.click({target:{closest:()=>({dataset:{action:"practice"}})}});
assert.equal(openedPractice,"detector-selection-effects");
handlers.click({target:{closest:()=>({dataset:{concept:"cosmic-merger-rates"}})}});
assert.equal(selectedConcept,"cosmic-merger-rates");
// A saved previous selection must not auto-open on the next visit.
const secondHost={innerHTML:"",addEventListener(){},querySelector:()=>null};
const reopened=X.mount({host:secondHost,data:journey,concepts:conceptData.concepts,sources:sourceData.sources,
 model:M,storage,getEvidence:()=>e});
assert.equal(reopened.snapshot().stage,null,"Reloading does not automatically reopen the last question");
assert.equal(reopened.snapshot().done.length,1,"Self-reported exploration is preserved across visits");
assert.doesNotMatch(secondHost.innerHTML,/class="research-stage-detail"/,"Reloaded UI also starts at the six-card picker");
const before=await fs.readFile("index.html","utf8");
assert.ok(before.includes('id="research-experience"')&&before.indexOf('id="research-experience"')>before.indexOf('id="practice-panel"'),"Integrated pathway belongs to Practice");
assert.equal((before.match(/data-atlas-tab=/g)||[]).length,3,"No unnecessary fourth tab");
const graph=await fs.readFile("constellation.js","utf8");
assert.ok(graph.includes("relationData")&&graph.includes("scientific-relations")&&graph.includes("type:\"prerequisite\""),"Graph distinguishes typed scientific relations from containment");
console.log("Passed: six non-linear research question cards, no default/remembered auto-selection, preserved progress, 30 authored problems, toy models, evidence and local notebook inside Practice.");
